-- Ajuste os nomes de tabela/coluna abaixo para o seu schema real
-- antes de rodar. Isto é um template gerado a partir da planilha.

INSERT INTO tickets (id_legado, cliente, bloqueio_motivo, bloqueio_tipo) VALUES (3357, 'CAMINHONETE & CIA', 'Segundo a Giovanna só quer seguir com teste de pedido quando buscarmos o preco de venda no SANKHYA', NULL) ON CONFLICT (id_legado) DO UPDATE SET cliente = EXCLUDED.cliente, bloqueio_motivo = EXCLUDED.bloqueio_motivo;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3357, 'produto', 'importacao_produtos', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3357, 'produto', 'cadastro_produto', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3357, 'produto', 'categoria_atributos', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3357, 'produto', 'variacao', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3357, 'produto', 'publicacao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3357, 'operacao', 'estoque', 'bloqueado') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3357, 'operacao', 'loja_virtual', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3357, 'operacao', 'logistica', 'nao_mapeado') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3357, 'comercial', 'gestao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3357, 'comercial', 'metrica', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3357, 'comercial', 'precificacao', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3357, 'pos_venda', 'treinamento_importacao_anuncios', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3357, 'pos_venda', 'importacao_anuncios', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3357, 'pos_venda', 'virada', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3357, 'pos_venda', 'acompanhamento', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;

INSERT INTO tickets (id_legado, cliente, bloqueio_motivo, bloqueio_tipo) VALUES (3351, 'A2 HOSPITALAR', 'Problemas de estoque', NULL) ON CONFLICT (id_legado) DO UPDATE SET cliente = EXCLUDED.cliente, bloqueio_motivo = EXCLUDED.bloqueio_motivo;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3351, 'produto', 'importacao_produtos', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3351, 'produto', 'cadastro_produto', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3351, 'produto', 'categoria_atributos', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3351, 'produto', 'variacao', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3351, 'produto', 'publicacao', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3351, 'operacao', 'estoque', 'bloqueado') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3351, 'operacao', 'loja_virtual', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3351, 'operacao', 'logistica', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3351, 'comercial', 'gestao', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3351, 'comercial', 'metrica', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3351, 'comercial', 'precificacao', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3351, 'pos_venda', 'treinamento_importacao_anuncios', 'nao_mapeado') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3351, 'pos_venda', 'importacao_anuncios', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3351, 'pos_venda', 'virada', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3351, 'pos_venda', 'acompanhamento', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;

INSERT INTO tickets (id_legado, cliente, bloqueio_motivo, bloqueio_tipo) VALUES (3345, 'BCM REFRIGERAÇÃO', NULL, NULL) ON CONFLICT (id_legado) DO UPDATE SET cliente = EXCLUDED.cliente, bloqueio_motivo = EXCLUDED.bloqueio_motivo;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3345, 'produto', 'importacao_produtos', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3345, 'produto', 'cadastro_produto', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3345, 'produto', 'categoria_atributos', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3345, 'produto', 'variacao', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3345, 'produto', 'publicacao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3345, 'operacao', 'estoque', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3345, 'operacao', 'loja_virtual', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3345, 'operacao', 'logistica', 'nao_mapeado') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3345, 'comercial', 'gestao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3345, 'comercial', 'metrica', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3345, 'comercial', 'precificacao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3345, 'pos_venda', 'treinamento_importacao_anuncios', 'nao_aplicavel') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3345, 'pos_venda', 'importacao_anuncios', 'nao_aplicavel') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3345, 'pos_venda', 'virada', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3345, 'pos_venda', 'acompanhamento', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;

INSERT INTO tickets (id_legado, cliente, bloqueio_motivo, bloqueio_tipo) VALUES (3337, 'ALWAYS FIT', NULL, NULL) ON CONFLICT (id_legado) DO UPDATE SET cliente = EXCLUDED.cliente, bloqueio_motivo = EXCLUDED.bloqueio_motivo;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3337, 'produto', 'importacao_produtos', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3337, 'produto', 'cadastro_produto', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3337, 'produto', 'categoria_atributos', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3337, 'produto', 'variacao', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3337, 'produto', 'publicacao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3337, 'operacao', 'loja_virtual', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3337, 'comercial', 'gestao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3337, 'comercial', 'metrica', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3337, 'comercial', 'precificacao', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3337, 'pos_venda', 'importacao_anuncios', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3337, 'pos_venda', 'virada', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3337, 'pos_venda', 'acompanhamento', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;

INSERT INTO tickets (id_legado, cliente, bloqueio_motivo, bloqueio_tipo) VALUES (2754, 'LUITEX FERRAMENTAS', 'Migração de painel', NULL) ON CONFLICT (id_legado) DO UPDATE SET cliente = EXCLUDED.cliente, bloqueio_motivo = EXCLUDED.bloqueio_motivo;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (2754, 'produto', 'importacao_produtos', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (2754, 'operacao', 'estoque', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;

INSERT INTO tickets (id_legado, cliente, bloqueio_motivo, bloqueio_tipo) VALUES (3332, 'G.R.A COMÉRCIO', NULL, NULL) ON CONFLICT (id_legado) DO UPDATE SET cliente = EXCLUDED.cliente, bloqueio_motivo = EXCLUDED.bloqueio_motivo;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3332, 'produto', 'importacao_produtos', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3332, 'produto', 'cadastro_produto', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3332, 'produto', 'categoria_atributos', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3332, 'produto', 'variacao', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3332, 'produto', 'publicacao', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3332, 'operacao', 'estoque', 'bloqueado') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3332, 'operacao', 'loja_virtual', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3332, 'operacao', 'logistica', 'nao_mapeado') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3332, 'comercial', 'gestao', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3332, 'comercial', 'metrica', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3332, 'comercial', 'precificacao', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3332, 'pos_venda', 'treinamento_importacao_anuncios', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3332, 'pos_venda', 'importacao_anuncios', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3332, 'pos_venda', 'virada', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3332, 'pos_venda', 'acompanhamento', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;

INSERT INTO tickets (id_legado, cliente, bloqueio_motivo, bloqueio_tipo) VALUES (3331, 'KADRI', 'Integração de expedição (parceiro logistico)', NULL) ON CONFLICT (id_legado) DO UPDATE SET cliente = EXCLUDED.cliente, bloqueio_motivo = EXCLUDED.bloqueio_motivo;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3331, 'produto', 'importacao_produtos', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3331, 'produto', 'cadastro_produto', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3331, 'produto', 'categoria_atributos', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3331, 'produto', 'variacao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3331, 'produto', 'publicacao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3331, 'operacao', 'estoque', 'bloqueado') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3331, 'operacao', 'loja_virtual', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3331, 'operacao', 'logistica', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3331, 'comercial', 'gestao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3331, 'comercial', 'metrica', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3331, 'comercial', 'precificacao', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3331, 'pos_venda', 'treinamento_importacao_anuncios', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3331, 'pos_venda', 'importacao_anuncios', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3331, 'pos_venda', 'virada', 'parcial') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3331, 'pos_venda', 'acompanhamento', 'parcial') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;

INSERT INTO tickets (id_legado, cliente, bloqueio_motivo, bloqueio_tipo) VALUES (3330, 'INSTITUTO ALFA E BETO', 'Vai usar WMS', NULL) ON CONFLICT (id_legado) DO UPDATE SET cliente = EXCLUDED.cliente, bloqueio_motivo = EXCLUDED.bloqueio_motivo;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3330, 'produto', 'importacao_produtos', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3330, 'produto', 'cadastro_produto', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3330, 'produto', 'categoria_atributos', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3330, 'produto', 'publicacao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3330, 'operacao', 'estoque', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3330, 'operacao', 'loja_virtual', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3330, 'operacao', 'logistica', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3330, 'comercial', 'gestao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3330, 'comercial', 'metrica', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3330, 'comercial', 'precificacao', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3330, 'pos_venda', 'treinamento_importacao_anuncios', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3330, 'pos_venda', 'importacao_anuncios', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3330, 'pos_venda', 'virada', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3330, 'pos_venda', 'acompanhamento', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;

INSERT INTO tickets (id_legado, cliente, bloqueio_motivo, bloqueio_tipo) VALUES (3325, 'SUPERNOVA', 'Treinamentos', NULL) ON CONFLICT (id_legado) DO UPDATE SET cliente = EXCLUDED.cliente, bloqueio_motivo = EXCLUDED.bloqueio_motivo;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3325, 'produto', 'importacao_produtos', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3325, 'produto', 'cadastro_produto', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3325, 'produto', 'categoria_atributos', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3325, 'produto', 'publicacao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3325, 'operacao', 'estoque', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3325, 'operacao', 'loja_virtual', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3325, 'operacao', 'logistica', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3325, 'comercial', 'gestao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3325, 'pos_venda', 'treinamento_importacao_anuncios', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3325, 'pos_venda', 'importacao_anuncios', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3325, 'pos_venda', 'virada', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3325, 'pos_venda', 'acompanhamento', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;

INSERT INTO tickets (id_legado, cliente, bloqueio_motivo, bloqueio_tipo) VALUES (3306, 'PRINCIPE DA PAZ', 'Faturamento automatico no Sankhya', NULL) ON CONFLICT (id_legado) DO UPDATE SET cliente = EXCLUDED.cliente, bloqueio_motivo = EXCLUDED.bloqueio_motivo;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3306, 'produto', 'importacao_produtos', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3306, 'produto', 'cadastro_produto', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3306, 'produto', 'categoria_atributos', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3306, 'produto', 'variacao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3306, 'produto', 'publicacao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3306, 'operacao', 'estoque', 'bloqueado') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3306, 'operacao', 'loja_virtual', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3306, 'operacao', 'logistica', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3306, 'comercial', 'gestao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3306, 'comercial', 'metrica', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3306, 'comercial', 'precificacao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3306, 'pos_venda', 'treinamento_importacao_anuncios', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3306, 'pos_venda', 'importacao_anuncios', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3306, 'pos_venda', 'virada', 'parcial') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3306, 'pos_venda', 'acompanhamento', 'parcial') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;

INSERT INTO tickets (id_legado, cliente, bloqueio_motivo, bloqueio_tipo) VALUES (3305, 'VIA STAR', 'Sem atulizações', NULL) ON CONFLICT (id_legado) DO UPDATE SET cliente = EXCLUDED.cliente, bloqueio_motivo = EXCLUDED.bloqueio_motivo;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3305, 'produto', 'importacao_produtos', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3305, 'produto', 'cadastro_produto', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3305, 'produto', 'categoria_atributos', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3305, 'produto', 'variacao', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3305, 'produto', 'publicacao', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3305, 'operacao', 'estoque', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3305, 'operacao', 'loja_virtual', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3305, 'operacao', 'logistica', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3305, 'comercial', 'gestao', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3305, 'comercial', 'metrica', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3305, 'comercial', 'precificacao', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3305, 'pos_venda', 'treinamento_importacao_anuncios', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3305, 'pos_venda', 'importacao_anuncios', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3305, 'pos_venda', 'virada', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3305, 'pos_venda', 'acompanhamento', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;

INSERT INTO tickets (id_legado, cliente, bloqueio_motivo, bloqueio_tipo) VALUES (3304, 'GOLD SERVICE', 'Pendente variação /Alinhamento com o Lucas', NULL) ON CONFLICT (id_legado) DO UPDATE SET cliente = EXCLUDED.cliente, bloqueio_motivo = EXCLUDED.bloqueio_motivo;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3304, 'produto', 'importacao_produtos', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3304, 'produto', 'cadastro_produto', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3304, 'produto', 'categoria_atributos', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3304, 'produto', 'variacao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3304, 'produto', 'publicacao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3304, 'operacao', 'estoque', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3304, 'operacao', 'loja_virtual', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3304, 'operacao', 'logistica', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3304, 'comercial', 'gestao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3304, 'comercial', 'metrica', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3304, 'comercial', 'precificacao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3304, 'pos_venda', 'treinamento_importacao_anuncios', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3304, 'pos_venda', 'importacao_anuncios', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3304, 'pos_venda', 'virada', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3304, 'pos_venda', 'acompanhamento', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;

INSERT INTO tickets (id_legado, cliente, bloqueio_motivo, bloqueio_tipo) VALUES (3300, 'REAL EQUIPAMENTOS', 'Taxa porto', NULL) ON CONFLICT (id_legado) DO UPDATE SET cliente = EXCLUDED.cliente, bloqueio_motivo = EXCLUDED.bloqueio_motivo;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3300, 'produto', 'importacao_produtos', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3300, 'produto', 'cadastro_produto', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3300, 'produto', 'categoria_atributos', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3300, 'produto', 'variacao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3300, 'produto', 'publicacao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3300, 'operacao', 'estoque', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3300, 'operacao', 'loja_virtual', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3300, 'operacao', 'logistica', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3300, 'comercial', 'gestao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3300, 'comercial', 'precificacao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3300, 'pos_venda', 'treinamento_importacao_anuncios', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3300, 'pos_venda', 'importacao_anuncios', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3300, 'pos_venda', 'virada', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3300, 'pos_venda', 'acompanhamento', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;

INSERT INTO tickets (id_legado, cliente, bloqueio_motivo, bloqueio_tipo) VALUES (3299, 'CASA DO PAPEL', NULL, NULL) ON CONFLICT (id_legado) DO UPDATE SET cliente = EXCLUDED.cliente, bloqueio_motivo = EXCLUDED.bloqueio_motivo;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3299, 'produto', 'importacao_produtos', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3299, 'produto', 'cadastro_produto', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3299, 'produto', 'categoria_atributos', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3299, 'produto', 'variacao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3299, 'produto', 'publicacao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3299, 'operacao', 'estoque', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3299, 'operacao', 'loja_virtual', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3299, 'operacao', 'logistica', 'nao_mapeado') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3299, 'comercial', 'gestao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3299, 'comercial', 'metrica', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3299, 'comercial', 'precificacao', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3299, 'pos_venda', 'treinamento_importacao_anuncios', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3299, 'pos_venda', 'importacao_anuncios', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3299, 'pos_venda', 'virada', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3299, 'pos_venda', 'acompanhamento', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;

INSERT INTO tickets (id_legado, cliente, bloqueio_motivo, bloqueio_tipo) VALUES (3290, 'LAR PLÁSTICOS', 'Sem infomações', NULL) ON CONFLICT (id_legado) DO UPDATE SET cliente = EXCLUDED.cliente, bloqueio_motivo = EXCLUDED.bloqueio_motivo;

INSERT INTO tickets (id_legado, cliente, bloqueio_motivo, bloqueio_tipo) VALUES (3286, 'MA HOSPITALAR', NULL, NULL) ON CONFLICT (id_legado) DO UPDATE SET cliente = EXCLUDED.cliente, bloqueio_motivo = EXCLUDED.bloqueio_motivo;

INSERT INTO tickets (id_legado, cliente, bloqueio_motivo, bloqueio_tipo) VALUES (3278, 'LEGBOX', 'Estão perdido com a expedição', NULL) ON CONFLICT (id_legado) DO UPDATE SET cliente = EXCLUDED.cliente, bloqueio_motivo = EXCLUDED.bloqueio_motivo;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3278, 'produto', 'importacao_produtos', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3278, 'produto', 'cadastro_produto', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3278, 'produto', 'categoria_atributos', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3278, 'produto', 'variacao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3278, 'produto', 'publicacao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3278, 'operacao', 'estoque', 'bloqueado') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3278, 'operacao', 'loja_virtual', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3278, 'operacao', 'logistica', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3278, 'comercial', 'gestao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3278, 'comercial', 'metrica', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3278, 'comercial', 'precificacao', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3278, 'pos_venda', 'treinamento_importacao_anuncios', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3278, 'pos_venda', 'importacao_anuncios', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3278, 'pos_venda', 'virada', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3278, 'pos_venda', 'acompanhamento', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;

INSERT INTO tickets (id_legado, cliente, bloqueio_motivo, bloqueio_tipo) VALUES (3267, 'V G AUTO PEÇAS', 'Pendente treinamento Geral', NULL) ON CONFLICT (id_legado) DO UPDATE SET cliente = EXCLUDED.cliente, bloqueio_motivo = EXCLUDED.bloqueio_motivo;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3267, 'produto', 'importacao_produtos', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3267, 'produto', 'cadastro_produto', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3267, 'produto', 'categoria_atributos', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3267, 'produto', 'publicacao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3267, 'operacao', 'estoque', 'bloqueado') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3267, 'operacao', 'loja_virtual', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3267, 'operacao', 'logistica', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3267, 'comercial', 'gestao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3267, 'comercial', 'metrica', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3267, 'comercial', 'precificacao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3267, 'pos_venda', 'treinamento_importacao_anuncios', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3267, 'pos_venda', 'importacao_anuncios', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3267, 'pos_venda', 'virada', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3267, 'pos_venda', 'acompanhamento', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;

INSERT INTO tickets (id_legado, cliente, bloqueio_motivo, bloqueio_tipo) VALUES (3239, 'EPI COMERCIO', 'OK', NULL) ON CONFLICT (id_legado) DO UPDATE SET cliente = EXCLUDED.cliente, bloqueio_motivo = EXCLUDED.bloqueio_motivo;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3239, 'produto', 'cadastro_produto', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3239, 'produto', 'categoria_atributos', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3239, 'produto', 'variacao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3239, 'produto', 'publicacao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3239, 'comercial', 'gestao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3239, 'comercial', 'metrica', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3239, 'comercial', 'precificacao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3239, 'pos_venda', 'importacao_anuncios', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3239, 'pos_venda', 'virada', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3239, 'pos_venda', 'acompanhamento', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;

INSERT INTO tickets (id_legado, cliente, bloqueio_motivo, bloqueio_tipo) VALUES (3236, 'ORANGE POWERSPORTS', 'Ativação de contas', NULL) ON CONFLICT (id_legado) DO UPDATE SET cliente = EXCLUDED.cliente, bloqueio_motivo = EXCLUDED.bloqueio_motivo;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3236, 'produto', 'importacao_produtos', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3236, 'produto', 'cadastro_produto', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3236, 'produto', 'categoria_atributos', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3236, 'produto', 'variacao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3236, 'produto', 'publicacao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3236, 'operacao', 'estoque', 'parcial') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3236, 'operacao', 'loja_virtual', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3236, 'operacao', 'logistica', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3236, 'comercial', 'gestao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3236, 'comercial', 'precificacao', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3236, 'pos_venda', 'treinamento_importacao_anuncios', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3236, 'pos_venda', 'importacao_anuncios', 'parcial') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3236, 'pos_venda', 'virada', 'parcial') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3236, 'pos_venda', 'acompanhamento', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;

INSERT INTO tickets (id_legado, cliente, bloqueio_motivo, bloqueio_tipo) VALUES (3222, 'BUQ CARE', 'Cliente cancelou Snkhya', NULL) ON CONFLICT (id_legado) DO UPDATE SET cliente = EXCLUDED.cliente, bloqueio_motivo = EXCLUDED.bloqueio_motivo;

INSERT INTO tickets (id_legado, cliente, bloqueio_motivo, bloqueio_tipo) VALUES (3217, 'MYPET', NULL, NULL) ON CONFLICT (id_legado) DO UPDATE SET cliente = EXCLUDED.cliente, bloqueio_motivo = EXCLUDED.bloqueio_motivo;

INSERT INTO tickets (id_legado, cliente, bloqueio_motivo, bloqueio_tipo) VALUES (3205, 'TECIDOS MIRAMONTES', NULL, NULL) ON CONFLICT (id_legado) DO UPDATE SET cliente = EXCLUDED.cliente, bloqueio_motivo = EXCLUDED.bloqueio_motivo;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3205, 'produto', 'cadastro_produto', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3205, 'produto', 'variacao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3205, 'produto', 'publicacao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3205, 'operacao', 'estoque', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3205, 'comercial', 'gestao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3205, 'comercial', 'precificacao', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3205, 'pos_venda', 'treinamento_importacao_anuncios', 'feito') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;
INSERT INTO checklist_items (ticket_id_legado, categoria, item, status) VALUES (3205, 'pos_venda', 'importacao_anuncios', 'pendente') ON CONFLICT (ticket_id_legado, item) DO UPDATE SET status = EXCLUDED.status;

INSERT INTO tickets (id_legado, cliente, bloqueio_motivo, bloqueio_tipo) VALUES (3186, 'THERMO KLIMA', 'OK', NULL) ON CONFLICT (id_legado) DO UPDATE SET cliente = EXCLUDED.cliente, bloqueio_motivo = EXCLUDED.bloqueio_motivo;